<br>
</td></tr></table>
</td></tr></table>
</td>
<td align="center" valign="top">


<table cellpadding="2" cellspacing="1" width="125" border="1">
<tr><td>
<a href="/index.php">Home</a>
</td></tr>
<tr><td>
<a href="/applets.php">Applets</a>
</td></tr>
<tr><td>
<a href="/revealed.php">About: Noj</a>
</td></tr>
<tr><td>
<a href="/media.php">Media</a>
</td></tr>
<tr><td>
<a href="">stuff</a>
</td></tr>
<tr><td>
<a href="">stuff</a>
</td></tr>
</table>


<br>
<img src="/images/notecoffee.png">

</td></tr>
</table>
</tr></td>
<tr><td align="center">
Copyright <a href="/contact.php">Noj</a> © 2005
<br><br>
</td></tr>
</table>
</center>
</body>
</html>
