<body background="images/bg.png">
<center>
<table width="720" cellpadding="10" cellspacing="0">
<tr><td bgcolor="black" background="http://noj.ugtech.net/images/head.png" valign="bottom">
<br><br>
<script src="http://noj.ugtech.net/src/phrase.js" type='text/javascript'>
document.write(space+text[increment]);
</script>
</tr></td>
<tr>
<td>

<table width="100%" cellspacing="1" cellpadding="4">
<tr><td align="center">
<table width="475" cellspacing="0" cellpadding="0" border="0">
<tr><td align="center" style="background: url('http://noj.ugtech.net/images/bitchpic.png');">
<table width="450" cellspacing="0" cellpadding="25" border="0">
<tr><td valign="top">