<html>
<head>
<title>
<?php
echo "$titleCookie";
?>
</title>
<link rel=stylesheet href="main.css" TYPE="text/css">
</head>
<body bgcolor="#8a8a8a">
<!--bgcolor="#5B7CD3" -->
<center>
<table width="720" cellpadding="10" cellspacing="0">

<tr><td bgcolor="black" background="head.png" valign="bottom">
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<?php
include('./inc/quote.inc');
?>
</tr></td>
<tr>
<td>

<table width="100%" cellspacing="1" cellpadding="4">
<tr><td align="center">

<table width="475" cellspacing="0" cellpadding="0" border="0">
<tr><td align="center" style="background: url('bitchpic.png');">

<table width="450" cellspacing="0" cellpadding="25" border="0">
<tr><td valign="top">



<?php
echo "$contentCookie";
?>

<br>

</td></tr></table>

</td></tr></table>

</td>
<td align="center" valign="top">

<?php
include('./inc/linkage.inc');
?>

<br>
<img src="/notecoffee.png">

</td></tr>
</table>

</tr></td>
<tr><td align="center">
Copyright <a href="/contact.php">Noj</a> &copy 2005
<br><br>
</td></tr>
</table>
</center>
</body>
</html>
